---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: 2.18.0
      sourceRef:
        kind: HelmRepository
        name: dirsigler
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.11
    env:
      - name: UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
        value: "true"
      - name: TZ
        value: "${TIMEZONE}"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/icon: mdi:chart-line
        hajimari.io/appName: "Uptime Kuma"
        hajimari.io/group: "monitoring"
      hosts:
        - host: &host "kuma-monitoring.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      storageClassName: local-hostpath
      size: 2Gi
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
