---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: node-red
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: node-red
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nodered/node-red
      tag: 3.1.3
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"

    service:
      main:
        ports:
          http:
            port: &port 1880

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:nodejs
          hajimari.io/appName: "Node-RED"
        hosts:
          - host: &host "node.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: node-red
                    port:
                      number: *port
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        storageClass: local-hostpath
        accessMode: ReadWriteOnce
        size: 1Gi

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 500Mi

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
