---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: influxdb-data-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: influxdb-data2-vol
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 20Gi
