---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  interval: 25m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb2
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    image:
      repository: docker.io/library/influxdb
      tag: 2.5.1
      pullPolicy: IfNotPresent
    adminUser:
      create: true
      organization: sc
      bucket: default
      user: "admin"
      retention_policy: "0s"
      existingSecret: influxdb-secret
    pdb:
      create: false
    env:
      - name: TZ
        value: "${TIMEZONE}"
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Influx DB"
        hajimari.io/icon: "database"
        hajimari.io/group: "databases"
      hosts:
        - &host "influx.mathiasuhl.com"
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      useExisting: true
      name: influxdb2-data
    # resources:
    #   requests:
    #     cpu: 30m
    #     memory: 500M
