ansible_become_pass: ENC[AES256_GCM,data:44+uhO6+4Q==,iv:se+nag7NGMvcsafnK/0Kbwr4DKpRyjGrpY7Maut3rCE=,tag:a2nxTQdJ3n/kdEgiNV5T5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaG11VFZtQjlST2FVQjAv
            WEZweDBvQnRybnVaa2JET0pzZllUSTZTYVNvCkF5a2cvNmJlczVRNnovSEw4Rlc5
            THRGVzh5MGRHUkhsT3FGcE8vMFRzMXcKLS0tIFB3R0FxYTFBS2pJQksxWWhDbDI3
            T2ZqMDZTaFdiYXJSNUZNMXhsRTVvNDAKleaeha892JSiM3SoISOaRGy66vCrdicE
            JNWqDj6rG18LxhgdR6WGncJThsDAg4/+CSDG5tnde0WbADYrSRd7dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T21:39:11Z"
    mac: ENC[AES256_GCM,data:DHj3DGZDW3JlLVAmSq0oDtgYLpIOzVLVAXvpWjCzZsXYYzpFX+lHL1tIWG+C01iY7NsmlYFxAGtiiW0kuvy+u6RH6vTzPiPlBlZQs8q60OeRCgpxlmHgTpImbOuDugM4P/isK1W3Ki7UidhHEJqwkk5/JX82fSj2a/mvdbJG+pA=,iv:7rXthFCI3hcTB4fTpjEXmHA/FbRkTic8M9OcOlAKUzQ=,tag:fF6iymhAu8XMXHJ2YIjX8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
