ansible_become_pass: ENC[AES256_GCM,data:jJqBQpVQTw==,iv:ch4i/lH2+jA8xYysacsshtCqrHu3d2GbCr+/YDB0FSA=,tag:4XcIFcaocszH8DuGIUlSEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnU3dWWXJ6ek9QNCtSQ1pr
            WDJhNHIvN1h5YjhZYmx0UnNXM0o3eER5azE0CnFtWHhEWWkwVktqZVlva1RERlhn
            cEpDK1RCejVmOGM4WkVabUZLWXd3S2MKLS0tIFcyMjcvZnk2ak5GZ1Y4WklJZUc0
            am1QdHozOVVLVjZFa0FzaG16dUFMNkUKmXTOCOxqWHmXENZ2d8ylOwcp2CNmPDEy
            QUWblib79A2EIRLxrKsFuS5yTgk7ffdSJygKV0rKt2PlFhRQ81oY9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T21:39:11Z"
    mac: ENC[AES256_GCM,data:AZr/kkCFFPKU+R9emv720wsR0qc9LSgzSGYZNKETSxe8K0+AwFwnpV6F3vCMp6LhJpGcmkJp1v2SNkNW5Cim55+NX/XGQtw0OfXOmJpQZlymgqPSZdMRaHYZATADzlBDJzto5Xl50UbWz7SnAlMX4gVjKmOLUYYRkIaZhc3/8Wo=,iv:k+4g20ZbpIYWN/5JO7hKX81pD4WpTtospm+lNDptRRY=,tag:r/8nX5vdztvgIPg+WPpt3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
