ansible_become_pass: ENC[AES256_GCM,data:0dSZuFUY5Q==,iv:jAhLzdIhamb7XgnJcoYg67ib5NXuVGQefILmRkeYshg=,tag:oNj65R2FSo4oqUeOAZLa8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVTV0ZFJJQ1dqRWRWN1dj
            RElrQTdockQyWXlZTU9GQXp3b1hsT1IxS2hZCjhkL1dhc1Q5clhpVGN4UXlHRFBt
            S04rb3lGS3JCTmo2alJaTXR1SzZRREkKLS0tIHRTZTM5RHZyaFNBcmFrOGZkWXR2
            UWhsN2ZqRWp0LzJXZkN6blF4UG9YWEEKu8tIM9JDejvTdMLeDtJuYyBlImbAKuek
            UEdqKiP8I+FIRIQJk/pH873tFOuZJLPn+yVcq5RXkISCaruBcKjnxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T20:16:02Z"
    mac: ENC[AES256_GCM,data:CYZZqyszF+8lz+4flWiKNq622dRLbf4EVU/+D99VQCnJ2AWbRaXqP46fxkPvL/I/k5kGZ+JNbbfucNfaQr7QldH9MflGH3JgHI0g9ksR7ZELsEmVlUmsCrzIfQIalrU+PQm0a8XMLCsOxU5/yXIO6u8avK16jctgxvxyn3+FvDA=,iv:+oZ2paFdOzEDotTnuLkev2/oFTsbcgU2bmTgdAZwMyM=,tag:uQuVEF/2orFUPgbYowaNbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
