---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: 5.5.6
      sourceRef:
        kind: HelmRepository
        name: rm3l
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    # controller:
    #   replicas: 1
    #   #strategy: RollingUpdate
    #   strategy:
    #   annotations:
    #     reloader.stakater.com/auto: "true"
    image:
      # -- Image repository
      repository: adguard/adguardhome
      # -- Image pull policy
      pullPolicy: IfNotPresent
      # -- Image tag
      tag: v0.107.53
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.31.64"
        ports:
          http:
            port: 3000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
      dns-udp:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        ports:
          dns-udp:
            port: 53
            protocol: UDP

    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: mdi:shield-check
        hajimari.io/appName: "AdGuard Home"
      hosts:
        - host: &host "adg.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      config:
        enabled: true
        storageClass: local-hostpath
        accessMode: ReadWriteOnce
        size: 1Gi
      work:
        enabled: true
        storageClass: local-hostpath
        accessMode: ReadWriteOnce
        size: 1Gi
