---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: adguard-home
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: rm3l
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.43
      pullPolicy: IfNotPresent

    services:
      # Admin panel service
      adminPanel:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "192.168.31.64"
        port: 3000

      # DNS Services
      dns:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        tcp:
          port: 53
        udp:
          port: 53

    ingresses:
      adminPanel:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:shield-check
          hajimari.io/appName: "AdGuard Home"
        hosts:
          - host: &host "adg.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      volumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-hostpath

    bootstrapEnabled: true
    bootstrapConfig:
      bind_host: 0.0.0.0
      bind_port: 80
      users: []
      auth_attempts: 5
      block_auth_min: 15
      http_proxy: ""
      language: ""
      theme: auto
      dns:
        bind_hosts:
          - 0.0.0.0
        port: 53
        anonymize_client_ip: false
        protection_enabled: true
        blocking_mode: default
        blocking_ipv4: ""
        blocking_ipv6: ""
        upstream_dns:
          - https://dns.cloudflare.com/dns-query
          - tls://1dot1dot1dot1.cloudflare-dns.com
        bootstrap_dns:
          - 1.1.1.1
          - 1.0.0.1
        querylog_enabled: true
        filtering_enabled: true
