---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-adguard-home-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
    - hard            # Keep retrying if NFS server is temporarily unavailable
    - noatime         # Don't update access times, reduces write operations
    - nodiratime      # Don't update directory access times
    - tcp             # Use TCP for more reliable connection
    - rsize=262144    # Read buffer size (256KB, good for small DNS files)
    - wsize=262144    # Write buffer size (256KB)
    - timeo=600       # Timeout for NFS operations (60 seconds)
    - retrans=2       # Number of retries for NFS operations
    - noresvport      # Use new TCP port after network failure
    - nolock          # Disable NFS file locking
    - local_lock=none # Disable local file locking
    - actimeo=3       # Cache attributes for 3 seconds
    - nocto           # Disable close-to-open consistency
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_adguard_config"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi_nextcloud"
      subDir: "adguard"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-driver-nfs
