---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crystallnet
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  url: oci://harbor.crystalnet.org/charts
