---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crystallnet
  namespace: flux-system
spec:
  interval: 1h
  url: https://crystallnet-org.github.io/helm-charts/
