---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 1h
  url: https://home-assistant.github.io/helm-charts
