---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: true
      showAppGroups: false
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: false
      createCRAppSample: true

      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - monitoring
      customApps:
        - group: Media
          apps:
            - name: AdGuard
              url: 'http://192.168.31.25:3001/'
              icon: 'mdi:test-tube'
              info: Where the ads die
            - name: Kuma
              url: 'http://192.168.31.25:500/status/overview'
              icon: 'mdi:test-tube'
              info: Minimalistic Monitoring
            - name: Kuma
              url: 'http://192.168.31.25:500/status/overview'
              icon: 'mdi:test-tube'
              info: Minimalistic Monitoring
            - name: CasaOS
              url: 'http://192.168.31.25/#/'
              icon: 'mdi:test-tube'
              info: Casa OS
            - name: Unifi Console
              url: 'https://unifi.ui.com/consoles/245A4C9C82210000000005F03372000000000635C5AC00000000610F7B61:719882696/network/default/dashboard              '
              icon: 'mdi:test-tube'
              info: Network
      globalBookmarks:
        - group: Communicate
          bookmarks:
          - name: Fefe Blog
            url: 'https://blog.fefe.de/'
          - name: Heise
            url: 'https://heise.de'
          - name: Tageschau
            url: 'https://tageschau.de'
          - name: Golem
            url: 'https://golem.de'
    serviceAccount:
      create: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
