---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-driver-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_nextcloud_config"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi_nextcloud"
