---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: csi-driver-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nextcloud-data
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
    - no_root_squash
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_nextcloud_data"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi_nextcloud"
      subDir: "config"
