---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 60m
  chart:
    spec:
      chart: nextcloud
      version: 4.5.10
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 60m
  timeout: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nextcloud
      tag: stable
      pullPolicy: IfNotPresent
    replicaCount: 1
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: "nextcloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
          - "nextcloud.${SECRET_DOMAIN}"
    nextcloud:
      host: nextcloud.${SECRET_DOMAIN}
      phpConfigs:
        defaultConfigs:
          .htaccess: true
          redis.config.php: false
          apache-pretty-urls.config.php: true
          apcu.config.php: true
          apps.config.php: true
          autoconfig.php: true
          smtp.config.php: false
      # configs:
      #   custom.config.php: |-
      #     <?php
      #     $CONFIG = array (
      #       'overwriteprotocol' => 'https',
      #       'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
      #       'filelocking.enabled' => 'true',
      #       'loglevel' => '2',
      #       'enable_previews' => true,
      #       'trusted_domains' =>
      #         [
      #           'nextcloud',
      #           'nextcloud.${SECRET_DOMAIN}'
      #         ],
      #       'trusted_proxies' =>
      #         [
      #           'nginx'
      #         ],
      #       'forwarded_for_headers' =>
      #         [
      #           0 => 'X-Forwarded-For',
      #           1 => 'HTTP_X_FORWARDED_FOR',
      #         ],
      #       'default_phone_region' => 'DE',
      #     );
      strategy:
        type: Recreate

      extraEnv: []

    extraSidecarContainers:
      - name: nextcloud-logger
        image: busybox
        command: [/bin/sh, -c, 'while ! test -f "/run/nextcloud/data/nextcloud.log"; do sleep 1; done; tail -n+1 -f /run/nextcloud/data/nextcloud.log']
        volumeMounts:
        - name: nextcloud-data
          mountPath: /run/nextcloud/data
    nginx:
      enabled: false

    internalDatabase:
      enabled: true

    mariadb:
      enabled: true
    postgresql:
      enabled: false
    redis:
      enabled: false

    cronjob:
      enabled: false
      resources:
        limits:
          memory: 1024M
        requests:
          cpu: 40m
          memory: 900M

    service:
      type: ClusterIP
      port: 8080

    persistence:
      enabled: true
      existingClaim: "nextcloud-config"

      nextcloudData:
        enabled: true
        existingClaim: "nextcloud-data"

    resources:
      limits:
        memory: 512M
      requests:
        cpu: 10m
        memory: 334M

    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false

    hpa:
      enabled: false

    metrics:
      enabled: true
      replicaCount: 1
      https: false
      timeout: 5s

      image:
        repository: xperimental/nextcloud-exporter
        tag: 0.6.2
        pullPolicy: IfNotPresent

      service:
        type: ClusterIP
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9205"
        labels: {}

      resources:
        limits:
          memory: 64M
        requests:
          cpu: 10m
        memory: 64M

    rbac:
      enabled: false
      serviceaccount:
        create: true
        name: nextcloud-serviceaccount

    securityContext:
      fsGroup: 33

    containers:
      - name: nextcloud
        securityContext:
          runAsUser: 33
          runAsGroup: 33
