---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 60m
  chart:
    spec:
      chart: nextcloud
      version: 4.5.10
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
      interval: 60m
  timeout: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: nextcloud
      flavor: apache
      tag: stable
      pullPolicy: IfNotPresent

    replicaCount: 1

    ingress:
      enabled: true
      className: internal
      annotations:
        # Example annotations
        nginx.ingress.kubernetes.io/proxy-body-size: "4G"
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: "nextcloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - secretName: nextcloud-tls
          hosts:
            - "nextcloud.${SECRET_DOMAIN}"

    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
      username: admin
      password: changeme
      update: 0
      containerPort: 80
      datadir: /var/www/html/data
      persistence:
        enabled: true
        existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
      defaultConfigs:
        ".htaccess": "true"
        "redis.config.php": "true"
        "apache-pretty-urls.config.php": "true"
        "apcu.config.php": "true"
        "apps.config.php": "true"
        "autoconfig.php": "true"
        "smtp.config.php": "true"
      configs:
        custom.config.php: |
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'enable_previews' => true,
            'trusted_domains' =>
              [
                'nextcloud',
                'nextcloud.${SECRET_DOMAIN}'
              ],
            'trusted_proxies' =>
              [
                'nginx'
              ],
            'forwarded_for_headers' =>
              [
                0 => 'X-Forwarded-For',
                1 => 'HTTP_X_FORWARDED_FOR',
              ],
            'default_phone_region' => 'DE',
          );

    mariadb:
      enabled: true
      auth:
        database: nextcloud
        username: nextcloud
        password: changeme

    service:
      type: ClusterIP
      port: 8080

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    livenessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

    securityContext:
      fsGroup: 33

    containers:
      - name: nextcloud
        securityContext:
          runAsUser: 33
          runAsGroup: 33
