apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
stringData:
    postgres_username: ENC[AES256_GCM,data:whYF05zW6vyjPA==,iv:n9jaqvpXeLRAzhV9KO8hhNgrBmF5FgAdGVyHTDbcHIw=,tag:QcnkukipEmMSawKdRrYFfQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:a4zqVAH8Nn/LuDKLdd56enVvw2sp,iv:Z8diaRBjLOarHrOHJpstMvG7bqMv/6ZeedDi3GfWYT4=,tag:OnhioGpmYg2oxE6gMI01IA==,type:str]
    admin_username: ENC[AES256_GCM,data:hE0=,iv:pgntput9Qg+1Z87Ozc6QFK7IxOhH1Ogzqlp6MUiU6iY=,tag:dzW2XOIoiMxce4mYoy3CHw==,type:str]
    admin_password: ENC[AES256_GCM,data:u7fSTlDKq83gKQ==,iv:S6g7aIE5PEpjgd3dW0tTV/ZWN8L9JGq8qr1CAN4FDg4=,tag:VfkZm1Fsj7nlB+fWLMpNnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucG1MWThhQUo0dHJRR0dF
            L2MzV1d5WVUrcnFUaVZDdk9YZWJPSFFFc0Q4CkRsRHpFMXFQRlU5am5adHJ0aUcr
            d2srbnJmdUN6MmFYclJQNkdyRHUzYjQKLS0tIGwyWG1IRmgrdTdXWjdZR2NLMHVN
            dHAybTJEcWZFYVRydUpnM2RmMXFrRTQKuAn4LPDIc+pnzqc1q2buirkr46tyW/Xx
            9rMFin28snf43aElgUahY4racdaYv1J+igY9diD31S5Lu1IVUeqJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-01T19:38:40Z"
    mac: ENC[AES256_GCM,data:u+X2KOIWGwRmvTYj8OVmbTjIbhtul3d9I+VGL3P89hp6PZ5qeM1b3Q6w0s1i4vsBIh6rea/4HmiwrQy7CilllHBilXDXXst/oawKEI0135kjnt8efIq3aJZX8lAjXgRNeUG/MqnxKfixGnYbhipla3AWkmf+R6YSJfBk+HPum14=,iv:KcUA5KsJm1pztFDhahxvWm/Bd4SkfVjPhOahQZQlQ1U=,tag:5fb177V8Pa8glU24eIgy1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
