---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-driver-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
  server: "192.168.31.226"  # Your NFS server
  share: "/mnt/user/k8s_csi"  # Your NFS share
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard
  - proto=tcp
  - timeo=600
  - retrans=2
  - actimeo=10
  - noatime
  - nodiratime
  - intr
  - local_lock=none
