apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:KuYb0f8yJQ==,iv:0wse2xECWtQHBrsYenjDlhV1meOgX7qStOkv27hmQ2g=,tag:dWYVOOfCTYrtLuC4B+jwgQ==,type:str]
    admin-user: ENC[AES256_GCM,data:F9uiv7o=,iv:gg9J/Izcluw+ikaICpZWpid30Lz6WKl4FlS8KMJInhM=,tag:n0Y9A7FEnvpc4i+UOYauOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2STJiVjA0dEc3M1FyM3Zp
            TG1BYmdESUI0SEpNc2dvcWE4a2lQT3QvcjNjCklOTXF0ME01bTFxYkk3TEtSaU9H
            RDZ3cENzRUFuVFBRSXJ0MmRqYjBxYW8KLS0tIFNNSnkwUXpzZkhBUy80ZTJ4aTdO
            eFFUUE40cFhHLzc3OXphNmFpdW9iMXcKQVfh9++jicoKK0x7TyK/dpumP+u2IAW0
            Jn8fQQ8Ac87oiqEiGRhP5b7DGICVO9JMyO6I/iFKXB5e4nI9O9vFWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T21:40:28Z"
    mac: ENC[AES256_GCM,data:ORKNJ8IC9jdggl3b6k7J8pvoCHlTdzs0nhrmuA1q+O0G2H+z7G6PZ8qe18K66mg5u8ZBMbxEcIh2QwjJfPH8hzI0Hu1+RXFDiweDnG9O3tcsbxSHtzL2l2Kn8uYfgkMK1mxXgY6y1WekYUu0sQvzu3G0FJKctYvInTmgN/RZloE=,iv:OwoMVHdDN4GqdVk5rgW74MdAD3DSJt4OOxPiJ/NqGPI=,tag:hGAtx/fI2JiskDPV5Pt0PA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
