---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
      spec:
          chart: zigbee2mqtt
          version: '1.37.1'
          sourceRef:
              kind: HelmRepository
              name: zigbee2mqtt
              namespace: flux-system
          interval: 10m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: TZ
        value: "${TIMEZONE}"
      - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
        value: "zigbee2mqtt"
      - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
        value: true
      - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
        value: "mqtt://localhost:1883"
      - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
        value: "tcp://192.168.30.183:6638"
      - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
        value: true
    persistence:
      enabled: true
      storageClass: csi-driver-nfs
      size: 1Gi
      accessMode: ReadWriteOnce

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Zigbee2MQTT"
        hajimari.io/icon: zigbee
      hosts:
        - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    # Additional configuration might be needed depending on your specific Zigbee setup
    # You may want to add device mappings, serial port configurations, etc.
    # additionalVolumeMounts:
    #   - name: zigbee-device
    #     mountPath: "tcp://192.168.30.183:6638"

    # additionalVolumes:
    #   - name: zigbee-device
    #     hostPath:
    #       path: /dev/ttyUSB0

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

    # Optional: Configure node selector if you have a specific Zigbee coordinator
    # nodeSelector:
    #   zigbee-coordinator: "true"
