---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: zigbee2mqtt
      version: '2.0.0'
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
      interval: 10m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      - name: TZ
        value: "${TIMEZONE}"

    persistence:
      enabled: true
      storageClass: csi-driver-nfs
      size: 1Gi
      accessMode: ReadWriteOnce

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Zigbee2MQTT"
        hajimari.io/icon: zigbee
      hosts:
        - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    # Configuration for Zigbee2MQTT
    config:
      advanced:
        transmit_power: 20
        permit_join: true
        mqtt_server: mqtt://localhost:1883
        serial_port: tcp://192.168.30.183:6638
        frontend_enabled: true

      homeassistant:
        discovery_topic: "homeassistant"
        enabled: true

      serial:
        baudrate: 115200
        port: tcp://192.168.30.183:6638
        disable_led: true
        adapter: zstack

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
