apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:y5e6/LNDvLxVuza7mMem1n0BrL1xc6GT6RZTqdS9LH1J4AtAAHFniw==,iv:VsZk5JFnmEXhWCPXLHPdlWWZA/3f9VmX2x8lSfQ2ync=,tag:Uk7GdvVxyY1zjTgbOxUTig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWTZSeFNSRFB3MkpuWXpr
            OXlSQndIUG0xREVrOTlBSUxLSmR6ZWhpSWtVCnFxRmRYa0hDY1NHQ2pDTjN2SDhn
            ciszR0RPSWJmc0pwZkwvUFd5VENjcXMKLS0tIEovekFoQ0VRMG9JZ2RtV3M5ejc3
            SnpQLzFaQXAxN2xrUFNhN1JUOWl5TW8Kyi8+NZnMon3jxAugM0vqRpV/srxGhNnj
            m/gILpBXqPvKNVMDzjJkihfeTdiVr726M3xj0zoWL6kpnr+6jZAepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T21:40:23Z"
    mac: ENC[AES256_GCM,data:+G+n2PoVTJVk54aRuZEn6BOSqPtABgwX1ZNGYHD/KtEo+UKywFZ7iClpOTrkDlBV7zlLs218B8lhToe1YO+76dB3C3G95qpNmJM1XxnUzGo2iPpLi2L/rYyQf1/s4JsBlRAInZzmaT0CTQeMpM4O1cwj+ir8ncLgYChHkEo1BtY=,iv:IaLp2+QmA/6ReSDQ2d1/fDaGS0BExMyXNIG48KMerOA=,tag:k4Ofsn2HplaWWCw3/9zFVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
