apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:k8tRMaAscysi6ZddMEB71e6OTOtmTw/8qWpKHbvJC0p2rr6gayKw2Q==,iv:3SeUmi6bEyQ6+d0wzh0eTv+HxQnyqYBKdmO6ZicWl4E=,tag:wNmxpvkbHeHOIdi1LOswBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYU0xMVQvN3RPUXZ4cW1t
            WWdtZE9ndi9QalowRGcyVmxMVExacWNoeERRCjlMSVdkZ2NjWGtCOGtxVHphM08v
            UmpSQ3A4eHk1MTQ3N1hJbjg3Z1o0V1EKLS0tIDF3aUdIVzc2UEpSMXZ5UVV2dTdz
            SWxKbXpMSHZHOHpZQUFPdlZtcm4wVVUKeQy3tFsamEUh6Y7sB//YQua8y64ZNvIW
            ZFbckBoWVWsZrGgMMHu4CwU3sdUJNLYHlSX8gMM1KuXXOtQpxeZR1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T21:40:22Z"
    mac: ENC[AES256_GCM,data:1BsPLUZGtGLF1TKsrQI7SQe4AcfJgMEFRu3K3fKfqWan4fw1ZBC4SaeoN8OPw+jmyJC6juh8UIZG5DjVCihPxXTjGj/r49IcPiDLzcUslCk4gyvHgp0gwM2GT1HG2rGdTZQy+rs20yT10R+xuVY3V2XRKyawuPK78puSl1ZfP2s=,iv:neXcj2mq+gVPQk333SYrFCMjiGCvTiYxutaY+3CVM0g=,tag:I9LqVhTLnL8e2QmBhsKKtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
