---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: romm
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: romm
      version: 0.2.20
      sourceRef:
        kind: HelmRepository
        name: crystalnet
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: zurdi15/romm
      pullPolicy: IfNotPresent

    persistence:

      resources:
        enabled: true
        existingClaim: romm-resources

      database:
        enabled: true
        existingClaim: romm-database

      logs:
        enabled: true
        existingClaim: romm-logs

    mariadb:
      enabled: false

    redis:
      enabled: false
