---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: romm
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: romm
      version: 0.2.20
      sourceRef:
        kind: HelmRepository
        name: crystalnet
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: zurdi15/romm
      pullPolicy: IfNotPresent

    persistence:
      resources:
        enabled: true
        volumeClaimSpec:
          existingClaim: romm-resources
      logs:
        enabled: true
        volumeClaimSpec:
          existingClaim: romm-logs
      database:
        enabled: true
        volumeClaimSpec:
          existingClaim: romm-database

    ingress:
      enabled: true
      className: internal
      hosts:
        - host: &host "romm.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host

    mariadb:
      enabled: true
      auth:
        database: romm
        username: romm
      primary:
        persistence:
          enabled: true
          existingClaim: romm-database
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: true
      master:
        persistence:
          enabled: true
          existingClaim: romm-redis
