---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: romm
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: romm
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: crystalnet
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: zurdi15/romm
      #tag: v1.1.0
      pullPolicy: IfNotPresent

    serviceAccount:
      create: true

    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false

    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: mdi:nintendo-switch
        hajimari.io/appName: "ROMM"
        nginx.ingress.kubernetes.io/proxy-body-size: 256m
      hosts:
        - host: &host "romm.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - *host

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi

    persistence:
      resources:
        enabled: true
        volumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      logs:
        enabled: true
        volumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Mi

    mariadb:
      enabled: true
      auth:
        database: romm
        username: romm

      primary:
        persistence:
          enabled: true
          storageClass: local-hostpath
          size: 8Gi

    redis:
      enabled: true
      redisPort: 6379
      architecture: standalone
      auth:
        enabled: true

    romm:
      config:
        auth:
          enabled: true
          username: admin
        filesystem_watcher:
          enabled: true
          scan_delay: 5
        scheduled_tasks:
          filesystem_scan:
            enabled: true
            cron: "0 3 * * *"
          switch_titledb_update:
            enabled: true
            cron: "0 4 * * *"
          mame_xml_update:
            enabled: true
            cron: "0 5 * * *"
        database:
          type: mariadb

    mediaVolume:
      enabled: true
      name: roms
      readOnly: false
      volumeSpec:
        accessModes:
          - ReadWriteOnce
        capacity:
          storage: 100Gi
        storageClassName: local-hostpath

    env:
      - name: TZ
        value: "${TIMEZONE}"
