---
# PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-resources
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_resources"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-resources"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-logs
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_logs"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-logs"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-database
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_database"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-database"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-redis
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_redis"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-redis"
