---
# PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-res-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_resources"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-resources"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-data-pv
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_romm_database"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "romm-database"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-res
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: csi-driver-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-data
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: romm
    meta.helm.sh/release-namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-driver-nfs
