---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iobroker-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 10Gi
