---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iobroker
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    defaultPodOptions:
      hostname: iobroker
    controllers:
      main:
        type: statefulset
        strategy: RollingUpdate
        containers:
          main:
            nameOverride: iobroker
            image:
              repository: buanet/iobroker
              tag: v9.0.1
              pullPolicy: IfNotPresent
            hostAliases:
              - ip: "192.168.33.127"
                hostnames:
                - "gateway-2015-7066-8587.local"

            # -- environment variables.
            # See [image docs](https://docs.buanet.de/iobroker-docker-image/docs/) for more details.
            #env:
              # -- Config dir
              # DATA_FOLDER: "config"
            probes:
              # -- Liveness probe configuration
              # @default -- See below
              liveness:
                # -- Enable the liveness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own livenessProbe
                custom: false
                # -- sets the probe type when not using a custom probe
                # @default -- "TCP"
                type: TCP
                # -- The spec field contains the values for the default livenessProbe.
                # If you selected `custom: true`, this field holds the definition of the livenessProbe.
                # @default -- See below
                spec:
                  initialDelaySeconds: 20
                  periodSeconds: 30
                  timeoutSeconds: 1
                  failureThreshold: 3

              # -- Redainess probe configuration
              # @default -- See below
              readiness:
                # -- Enable the readiness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own readinessProbe
                custom: false
                # -- sets the probe type when not using a custom probe
                # @default -- "TCP"
                type: TCP
                # -- The spec field contains the values for the default readinessProbe.
                # If you selected `custom: true`, this field holds the definition of the readinessProbe.
                # @default -- See below
                spec:
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3

              # -- Startup probe configuration
              # @default -- See below
              startup:
                # -- Enable the startup probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own startupProbe
                custom: false
                # -- sets the probe type when not using a custom probe
                # @default -- "TCP"
                type: TCP
                # -- The spec field contains the values for the default startupProbe.
                # If you selected `custom: true`, this field holds the definition of the startupProbe.
                # @default -- See below
                spec:
                  initialDelaySeconds: 0
                  timeoutSeconds: 1
                  ## This means it has a maximum of 5*30=150 seconds to start up before it fails
                  periodSeconds: 5
                  failureThreshold: 30
    service:
      main:
        type: LoadBalancer
        ports:
          http:
            enabled: true
            port: 8081
          vis:
            enabled: true
            port: 8082
          nodered:
            enabled: true
            port: 1880
          states:
            enabled: true
            port: 9000
          objects:
            enabled: true
            port: 9001
          mqtt:
            protocol: TCP
            enabled: true
            port: 1883
          mqttws:
            protocol: TCP
            enabled: true
            port: 1884
          mqttshelly:
            protocol: TCP
            enabled: true
            port: 1885
          nuki:
            protocol: TCP
            enabled: true
            port: 51989
          alexa2-proxy:
            protocol: TCP
            enabled: true
            port: 51988
          avahi:
            protocol: TCP
            enabled: true
            port: 53388
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Iobroker"
        hosts:
          - host: "iobroker.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
          - host: "nodered.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: nodered
          - host: "vis.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: vis
        tls:
          - hosts:
            - "iobroker.${SECRET_DOMAIN}"
            - "nodered.${SECRET_DOMAIN}"
            - "vis.${SECRET_DOMAIN}"
    persistence:
      config-replicated:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        #storageClass: replicate-nvme
        storageClass: local-hostpath
        size: 10Gi
        globalMounts:
          - path: /opt/iobroker
            readOnly: false
    resources:
      requests:
        cpu: 30m
        memory: 2.5G
