---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 0.2.82
      sourceRef:
        kind: HelmRepository
        name: pajikos
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.10.2
    env:
      - name: TZ
        value: "${TIMEZONE}"
    service:
      type: ClusterIP
      port: 8123
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/icon: mdi:home-assistant
      hosts:
        - host: &host "hass.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      existingClaim: home-assistant-config
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.19.1
        env:
          - name: TZ
            value: "${TIMEZONE}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: internal
          annotations:
            hajimari.io/icon: mdi:microsoft-visual-studio-code
          hosts:
            - host: &codehost "hass-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *codehost
    resources:
      requests:
        cpu: 100m
        memory: 1000Mi
      limits:
        memory: 2000Mi
