apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Pjc+vJEJ8goHZc1iCnYYhkyrjvqMyevUB8zMdU0RFuK6/DP/,iv:zOz4eMGA9WEwTNKnd5D2KXnWzIVgCzttLT+vE6vTvzA=,tag:7Uodl+IDUvn9c8myKQxbnQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:aMjWlgBNlaK5WZIPkIN8Aw1Gt3w3CavEWr9u+mF3ixeTR1Ew83FxuTPv1dRz3V0UH51Tm80EQuNhVUjUY0o2tP0BUG+6ksKY9wiW03oQrDvcyzoCnMZ/PATooRSf8C+x/386lLiAmxqJTPJYN5wkcjtDmqARPLB+EldO+h8FQrhcmryhrC5KzqXbhgRIi17IX4D1u9vlb2VqfLW08GEix32eSqENw9cE4WWG+INhZg==,iv:ikeztCCZZzIFbq+aEaMuOWWGmxsm0rPSYnAsT8TzLa4=,tag:j/eLWXBxvF9huFKdoVzHQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUm1rbFBmcFFaUE44WlZk
            QjlSZk9YdXBHSk1uZGxPK05waVNVbHpLVjNVCnBzakwxN3ZwSUxOVVFCZUtOSlFo
            eUQxMzg4RmlWNEdNQWJIODFSSkVaV0EKLS0tIFBEclE4UWtxQys3Q0RZNmhVQjJq
            SElRN29jcjF6bHl6OUY2akpuS3hqalEKzx5CbNI8QLWJsBKOE2qmG7C8Gsc6/FUI
            vbrFM5k9TgL7s8zRMmsEY0Hm9y7ccMnwsx5w8Hqpys+oxPMyX5I1Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-28T20:17:13Z"
    mac: ENC[AES256_GCM,data:I3oGeTd37LpBRMqolzgDK2AOqkHB60VeMCzlNFRJoZiW+cgqZJ8t3Ze1lsMxVPk0EDQAcDKmD/LGaBOlmTsHw51D7Bv8CFL8btda0U4mla1H4s1nYUpWO+f7O8tWnYwqdqNthrO/s2eoN813sY8+4qKEupCVUOLfNVhJt3FMplk=,iv:zrFioYfHAWFmA6ZBY9069RPSPt0Orw80qixoLv2xCrQ=,tag:jQ+1snuBzbxp6+X/C/eb4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
