apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
stringData:
    db-username: ENC[AES256_GCM,data:CPMjKlSNJQ==,iv:GiX34pltxvLy8wmbFI2GDq9Zkl4HFe/2UcuQcO0aSAw=,tag:4daz0slJnD1cl5eWm/s/AQ==,type:str]
    db-password: ENC[AES256_GCM,data:vhCH5K3fh44O6ek8WhxhQlGJRA==,iv:+D3G2jftANTvKdwiQok2cEOwWS0mPrrZuyWWqFZ2do0=,tag:GSoRagq58xcfVCLYKNfWow==,type:str]
    admin-username: ENC[AES256_GCM,data:QCo=,iv:fQOqJcNqX2A9mTU3OL33bPXVrVgnVS9gh6KmU0PrnvE=,tag:d7BcIP0TXLrz6FTXxEhJHA==,type:str]
    admin-password: ENC[AES256_GCM,data:5xVOgxUB7iLpAg==,iv:cMuX7HDZoq3cmmRUO07pXwsULwFNLFwg0GYe57bLXs4=,tag:7Vh5PZFjYE9xTGq2pME+ww==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:VqXtxeTINlN+C6RRnSTYb7dJ4g==,iv:k2+raJ7+4qMOuL237kXRRnPA+GKSgC3rr4zII7STX1A=,tag:V1fjRs0yTanIZDh+I5bPhA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:NFud1m7Mtk5JzrZcHpANClB15A==,iv:BD8a5+aGcPOIERnKyK5JTuC/ZdD9PCWVsdtSqFSnV+I=,tag:lO1prGWLriWke+Oo8hTQzg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:FrN01LieVrkvZBOBUnCFIXPH/w==,iv:ZLVjhjYuGL1HHSa7KYX/w55I09DZuADXOOGP3JzpjEg=,tag:KTS8l7VjCEefTpU1EtH2og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucG1MWThhQUo0dHJRR0dF
            L2MzV1d5WVUrcnFUaVZDdk9YZWJPSFFFc0Q4CkRsRHpFMXFQRlU5am5adHJ0aUcr
            d2srbnJmdUN6MmFYclJQNkdyRHUzYjQKLS0tIGwyWG1IRmgrdTdXWjdZR2NLMHVN
            dHAybTJEcWZFYVRydUpnM2RmMXFrRTQKuAn4LPDIc+pnzqc1q2buirkr46tyW/Xx
            9rMFin28snf43aElgUahY4racdaYv1J+igY9diD31S5Lu1IVUeqJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-22T22:53:31Z"
    mac: ENC[AES256_GCM,data:k/1PGuJefKtC3p5ZO3Vyh7HAFHknhGCQhnTEun9CHON1YUTo+6Q5UM1idvpUE6b+C3lnyne/UPo4X9BlM8hn15OVgUhfNdqeAhqW6xIUsAGiI46XQUiLMtT0HF20Nj7xaa4Pp2i/Tx3+kdS9LHhJF3No4wDBTQ3Ib8EPZsU2TKk=,iv:tlUaqGoVjlsiFUsPVOgYxoZ4Kd/XJAiE0u1PbeQsnUw=,tag:JpE3X1uePpc1MjP8Ykw2Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
