apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-config
stringData:
    db-username: ENC[AES256_GCM,data:CPMjKlSNJQ==,iv:GiX34pltxvLy8wmbFI2GDq9Zkl4HFe/2UcuQcO0aSAw=,tag:4daz0slJnD1cl5eWm/s/AQ==,type:str]
    db-password: ENC[AES256_GCM,data:LGsf3wnkU/eGvYBi/wjRAh/gzD9p,iv:kn7Rv71SbKjVVkUkenJAubehl7YaMRKuKF6JOXW5Ccs=,tag:LMJ17snhOycVz7seymFY+g==,type:str]
    admin-username: ENC[AES256_GCM,data:QCo=,iv:fQOqJcNqX2A9mTU3OL33bPXVrVgnVS9gh6KmU0PrnvE=,tag:d7BcIP0TXLrz6FTXxEhJHA==,type:str]
    admin-password: ENC[AES256_GCM,data:5xVOgxUB7iLpAg==,iv:cMuX7HDZoq3cmmRUO07pXwsULwFNLFwg0GYe57bLXs4=,tag:7Vh5PZFjYE9xTGq2pME+ww==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:uBiaiqQkT43VeJTo0J4ya7DqJG/U,iv:lBP88tL5OM7qzQQeBo7WrXayNY9ONcxZqkdZctg1VLU=,tag:BGdF5qgmoQ79tasQDuQYEA==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:gYwllwzaBDEHJ8q9X6INk/wSKzGU,iv:BXIPqdddrEguvmUfSPMb9/kMTxDsobgi450ZkXz05BE=,tag:QqAmMxzgHZmoGDSHgg+PNQ==,type:str]
    mariadb-password: ENC[AES256_GCM,data:xBP2m7FBy8Ym7uQtd9Chj0X/XJjG,iv:mxR9LoWFfd/2Iz2bkhz4j0QMMLhy4Kt8WlTbAIT/+L4=,tag:O4XAE+7tR4whUEUYYd9FfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucG1MWThhQUo0dHJRR0dF
            L2MzV1d5WVUrcnFUaVZDdk9YZWJPSFFFc0Q4CkRsRHpFMXFQRlU5am5adHJ0aUcr
            d2srbnJmdUN6MmFYclJQNkdyRHUzYjQKLS0tIGwyWG1IRmgrdTdXWjdZR2NLMHVN
            dHAybTJEcWZFYVRydUpnM2RmMXFrRTQKuAn4LPDIc+pnzqc1q2buirkr46tyW/Xx
            9rMFin28snf43aElgUahY4racdaYv1J+igY9diD31S5Lu1IVUeqJWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-23T20:29:54Z"
    mac: ENC[AES256_GCM,data:HVjZbW/mPKYBecn+6i6CEYeidD2rcmYH/EugDn4eRbQ7R7UZbnSs8jEwpRSp/d3Y2cF3D4rRfJZL8HMGd5VKsKID4HYw/57ABL02r+62ziSjQJ9ASLKHoQ/5GAfqxZnHD8hqYkuuERiT9OZ4VUSeg0yHP/tOkswxaauaKBAZeuQ=,iv:nO5zdLf0GBGCjipg5zWcujhHHZcZgjZbiABVmIYBdfs=,tag:1Ca2bIBftS3bB2typdy4ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
