---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: office
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: "2.11.6"
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      className: internal
      annotations:
        hajimari.io/icon: mdi:file-document-multiple
      hosts:
        - host: &host "paperless.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistence:
      data:
        enabled: true
        retain: true
        storageClass: "local-hostpath"
        size: 10Gi
      log:
        enabled: true
        retain: true
        storageClass: "local-hostpath"
        size: 1Gi
      media:
        enabled: true
        retain: true
        volumeClaimSpec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi

    postgresql:
      enabled: true
      auth:
        database: paperless
        username: paperless
        existingSecret: paperless-ngx-secret
        secretKeys:
          adminPasswordKey: PAPERLESS_POSTGRES_PASSWORD
      primary:
        persistence:
          enabled: true
          storageClass: "local-hostpath"
          size: 8Gi

    redis:
      enabled: true
      auth:
        enabled: true
        existingSecret: paperless-ngx-secret
        existingSecretPasswordKey: PAPERLESS_REDIS_PASSWORD
      master:
        persistence:
          enabled: true
          storageClass: "local-hostpath"
          size: 2Gi

    env:
      TZ: Europe/Berlin
      PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
      PAPERLESS_OCR_LANGUAGES: "eng deu"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_ADMIN_USER:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_ADMIN_USER
      PAPERLESS_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_ADMIN_PASSWORD
      PAPERLESS_ADMIN_MAIL:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_ADMIN_EMAIL
      PAPERLESS_DBPASS:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_POSTGRES_PASSWORD
      PAPERLESS_REDIS_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_REDIS_PASSWORD

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1Gi
