---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: office
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.2.17
      sourceRef:
        kind: HelmRepository
        name: crystallnet
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: "2.4.3"
      pullPolicy: IfNotPresent

    config:
      auth:
        username: "mu"
        password:
          valueFrom:
            secretKeyRef:
              name: paperless-ngx-secret
              key: PAPERLESS_ADMIN_PASSWORD
        email:
          valueFrom:
            secretKeyRef:
              name: paperless-ngx-secret
              key: PAPERLESS_ADMIN_EMAIL
      paperless_url: "https://paperless.${SECRET_DOMAIN}"
      ocr_languages: ["eng", "deu"]
      consumer:
        recursive: true

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:file-document-multiple
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: paperless-ngx-data
        size: 15Gi
      media:
        enabled: true
        existingClaim: paperless-ngx-media
        size: 15Gi

    postgresql:
      enabled: true
      auth:
        database: paperless
        username: paperless
        password:
          valueFrom:
            secretKeyRef:
              name: paperless-ngx-secret
              key: PAPERLESS_POSTGRES_PASSWORD
      primary:
        persistence:
          enabled: true
          storageClass: local-hostpath
          size: 10Gi

    redis:
      enabled: true
      auth:
        enabled: true
        password:
          valueFrom:
            secretKeyRef:
              name: paperless-ngx-secret
              key: PAPERLESS_REDIS_PASSWORD
      master:
        persistence:
          enabled: true
          storageClass: local-hostpath
          size: 5Gi

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1Gi
