---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: office
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: 0.19.1
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: flux-system
  maxHistory: 1
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 1
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: "2.11.6"
      pullPolicy: IfNotPresent
    env:
      # -- Set the container timezone
      TZ: UTC
      PAPERLESS_SECRET_KEY:
        valueFrom:
          secretKeyRef:
            name: paperless-ngx-secret
            key: PAPERLESS_KEY
      PAPERLESS_URL: "https://paperless.${SECRET_DOMAIN}"
    service:
      # -- Configures service settings for the chart.
      # @default -- See [values.yaml](./values.yaml)
      main:
        ports:
          http:
            port: 8000
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:file-document-multiple
          nginx.ingress.kubernetes.io/proxy-body-size: 64m
        hosts:
          - host: &host "paperless.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        retain: true
        storageClass: "local-hostpath"
        accessMode: ReadWriteOnce
        size: 10Gi
      log:
        enabled: true
        retain: true
        storageClass: "local-hostpath"
        accessMode: ReadWriteOnce
        size: 1Gi
      media:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/media
        storageClass: "local-hostpath"
        accessMode: ReadWriteOnce
        size: 15Gi
      export:
        enabled: true
        mountPath: /usr/src/paperless/export
        storageClass: "local-hostpath"
        accessMode: ReadWriteOnce
        size: 1Gi
      consume:
        enabled: true
        retain: true
        mountPath: /usr/src/paperless/consume
        storageClass: "local-hostpath"
        accessMode: ReadWriteOnce
        size: 4Gi
    postgresql:
      enabled: false
    mariadb:
      enabled: false
      # auth:
      #   database: paperless
      #   username: paperless
      #   password: changeme
      #   rootPassword: changeme
      # primary:
      #   persistence:
      #     enabled: false
      #     storageClass: "local-hostpath"
      #     size: 8Gi
    redis:
      enabled: true
      auth:
      #  password: changeme
        enabled: true
      master:
        persistence:
          enabled: false
          storageClass: "local-hostpath"
          size: 2Gi
        replica:
          enabled: false
          replicaCount: 0
    resources:
      requests:
        cpu: 100m
        memory: 450Mi
      limits:
        memory: 2Gi
