apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-secret
    namespace: office
stringData:
    PAPERLESS_KEY: ENC[AES256_GCM,data:cyO+d5kIAKJaAFrWNF7LbioiZpkzWwOqEoUNxse7AUpz7k8iTcSXfmwRE5o8,iv:/Gr5K4/XwsWMU89EQOU5hqIHR68MrxvgOfkfMmQJhsk=,tag:YANjGHuLjineMDJnM01axw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nw624gkjpl0sattullahnekdswjcvsgarf8gwwyf9jdqc0zm9enqyp2pf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWFpRUlLN3lqci9JNVZK
            MDBkMlVzQmROeWI2ZklQcTV6QlEzSVdLQ0hBCmxsOFU1N2w4bnR3WWo5b2tYS05K
            ajJPSm1OYm1VT1Q3WXhpaitJbWZRVTAKLS0tIDNWcHBheTF3RE1Na2FRYzNMNjBl
            dVNsWE9YNXVMOWUzZWRLck12MkcwTjgKu8i4cws+XKmUQQA1uu6gbGt5asft5Yop
            b+2f4PvyWXwJn5tmpgcSmCmL12vNpI4FB58tar/Cl3f7m7IZDYFszw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-20T13:32:44Z"
    mac: ENC[AES256_GCM,data:xnD/5JyNzSyubUais6FqZbQ0tX7NuZmOyTnooLibB71Mg8hMxbCCr25e4Hy0LFrfnOCGBpVR1SZWDGvSAwxKAAIdNDP/ri4Mjr+ozRsA5nWP2hKY31zlMCx4mplZi7YFdQXbHszMyhPK99UlJ6Iw+bf2ATjW6gpZ4Mas76DvKTM=,iv:BDjZ0AAGPcyNoBp4TzJYXTvQ9sfr8sxqG/bWa5hh9ls=,tag:3/mxkAv6YQg4tkcl+0gx3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
