---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: csi-driver-nfs
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "nas_csi_open_webui_data"
    volumeAttributes:
      server: "192.168.31.226"
      share: "/mnt/user/k8s_csi"
      subDir: "open-webui-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-driver-nfs
